//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SystemSetting
    {
        public int ID { get; set; }
        public string GatewayNumber { get; set; }
        public string GatewayCompany { get; set; }
        public string GatewayUsername { get; set; }
        public string GatewayPassword { get; set; }
        public string GatewayIP { get; set; }
        public string EmailUsername { get; set; }
        public string EmailHost { get; set; }
        public string EmailPassword { get; set; }
        public string Email { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<System.TimeSpan> UpdateTime { get; set; }
        public Nullable<int> tryTime { get; set; }
        public Nullable<int> tryIntervalHour { get; set; }
        public Nullable<System.DateTime> ETime { get; set; }
        public string FK_EUserID { get; set; }
    }
}
