//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VASServiceMembership_NewsContent
    {
        public int ID { get; set; }
        public int FK_VASServiceID { get; set; }
        public int FK_NewsContentID { get; set; }
    
        public virtual tbl_NewsContent tbl_NewsContent { get; set; }
        public virtual tbl_VASServiceMembership tbl_VASServiceMembership { get; set; }
    }
}
