//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VASService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_VASService()
        {
            this.tbl_SendLog = new HashSet<tbl_SendLog>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_OwnerUserID { get; set; }
        public Nullable<int> FK_AggregatorID { get; set; }
        public Nullable<int> FK_HeadNumberID { get; set; }
        public Nullable<int> FK_VASServiceCategoryID { get; set; }
        public Nullable<bool> IsPardis { get; set; }
        public string theWholeNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ServiceName { get; set; }
        public string Remarks { get; set; }
        public string HeaderText { get; set; }
        public string FooterText { get; set; }
        public string WelcomeText { get; set; }
        public string GoodbyeText { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public Nullable<decimal> IMIEnduserTariff { get; set; }
        public string AggergatorServiceID { get; set; }
        public Nullable<bool> IsOnDemand { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_Aggregators tbl_Aggregators { get; set; }
        public virtual tbl_CategoryVASService tbl_CategoryVASService { get; set; }
        public virtual tbl_HeadNumber tbl_HeadNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SendLog> tbl_SendLog { get; set; }
        public virtual tbl_VASServiceMembership tbl_VASServiceMembership { get; set; }
        public virtual tbl_VASServiceOnDemand tbl_VASServiceOnDemand { get; set; }
    }
}
