//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VASServiceOnDemandManualContent
    {
        public int ID { get; set; }
        public Nullable<int> FK_VASServiceID { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string theText { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
    
        public virtual tbl_VASServiceOnDemand tbl_VASServiceOnDemand { get; set; }
    }
}
