//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReceiveLog
    {
        public int ID { get; set; }
        public Nullable<int> FK_HeadNumberID { get; set; }
        public string theText { get; set; }
        public string SenderMobile { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<int> FK_ReceiveDateID { get; set; }
        public string theWholeNumber { get; set; }
    
        public virtual tbl_Date tbl_Date { get; set; }
        public virtual tbl_HeadNumber tbl_HeadNumber { get; set; }
    }
}
