//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_AccessgroupUser = new HashSet<tbl_AccessgroupUser>();
            this.tbl_NewsContent = new HashSet<tbl_NewsContent>();
            this.tbl_VASService = new HashSet<tbl_VASService>();
            this.tbl_CRM = new HashSet<tbl_CRM>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDataAdmin { get; set; }
        public Nullable<bool> IsItemAdmin { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public string NationalID { get; set; }
        public string NationalNo { get; set; }
        public string Address { get; set; }
        public byte[] UserPhoto { get; set; }
        public Nullable<bool> IsReal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccessgroupUser> tbl_AccessgroupUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_NewsContent> tbl_NewsContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VASService> tbl_VASService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CRM> tbl_CRM { get; set; }
    }
}
