//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NewsContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_NewsContent()
        {
            this.tbl_VASServiceMembership_NewsContent = new HashSet<tbl_VASServiceMembership_NewsContent>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_OwnerUserID { get; set; }
        public string theText { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.TimeSpan> SendTime { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VASServiceMembership_NewsContent> tbl_VASServiceMembership_NewsContent { get; set; }
    }
}
