//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Menu
    {
        public int ID { get; set; }
        public string MenuTitle { get; set; }
        public Nullable<int> OrderIn { get; set; }
        public Nullable<int> FK_SiblingID { get; set; }
        public Nullable<int> FK_ParentID { get; set; }
        public string URL { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public string ClassName { get; set; }
        public string PageTitle { get; set; }
        public string IconStyle { get; set; }
        public Nullable<bool> IsLeaf { get; set; }
        public Nullable<bool> HasExtraInfo { get; set; }
        public string ExtraInfoStyle { get; set; }
    }
}
