//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VASServiceOnDemand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_VASServiceOnDemand()
        {
            this.tbl_VASServiceOnDemandManualContent = new HashSet<tbl_VASServiceOnDemandManualContent>();
        }
    
        public int FK_VASServiceID { get; set; }
        public Nullable<byte> theType { get; set; }
        public string theKey { get; set; }
        public Nullable<bool> IsSystematic { get; set; }
    
        public virtual tbl_VASService tbl_VASService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VASServiceOnDemandManualContent> tbl_VASServiceOnDemandManualContent { get; set; }
        public virtual tbl_VASServiceOnDemandSystematic tbl_VASServiceOnDemandSystematic { get; set; }
    }
}
