//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Date
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Date()
        {
            this.tbl_ReceiveLog = new HashSet<tbl_ReceiveLog>();
            this.tbl_SendLog = new HashSet<tbl_SendLog>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateG { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<byte> Day { get; set; }
        public Nullable<int> YearP { get; set; }
        public byte MonthP { get; set; }
        public Nullable<byte> DayP { get; set; }
        public string DateP { get; set; }
        public string WeekName { get; set; }
        public string WeekNameP { get; set; }
        public string MonthName { get; set; }
        public string MonthNameP { get; set; }
        public Nullable<byte> WeekNo { get; set; }
        public string Date { get; set; }
        public string WeekDayNo { get; set; }
        public int WeekDayNoID { get; set; }
        public Nullable<int> YearMonthP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ReceiveLog> tbl_ReceiveLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SendLog> tbl_SendLog { get; set; }
    }
}
