//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HeadNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HeadNumber()
        {
            this.tbl_ReceiveLog = new HashSet<tbl_ReceiveLog>();
            this.tbl_VASService = new HashSet<tbl_VASService>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_AggregatorID { get; set; }
        public string theNumber { get; set; }
        public Nullable<bool> IsParisType { get; set; }
        public Nullable<decimal> PardisServiceTariff { get; set; }
    
        public virtual tbl_Aggregators tbl_Aggregators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ReceiveLog> tbl_ReceiveLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VASService> tbl_VASService { get; set; }
    }
}
