//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Accessgroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Accessgroup()
        {
            this.tbl_AccessgroupMenu = new HashSet<tbl_AccessgroupMenu>();
            this.tbl_AccessgroupUser = new HashSet<tbl_AccessgroupUser>();
        }
    
        public int ID { get; set; }
        public string Desp { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<int> FK_UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccessgroupMenu> tbl_AccessgroupMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccessgroupUser> tbl_AccessgroupUser { get; set; }
    }
}
