//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccessgroupMenu
    {
        public int ID { get; set; }
        public Nullable<int> FK_AccessGroupID { get; set; }
        public Nullable<int> FK_MenuID { get; set; }
    
        public virtual tbl_Accessgroup tbl_Accessgroup { get; set; }
    }
}
