'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StartPage
    
    '''<summary>
    '''lblServiceCountSystematic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServiceCountSystematic As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblServiceCountManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServiceCountManual As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblServiceCountSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServiceCountSerial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblServiceCountNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServiceCountNews As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSendCountSystematic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSendCountSystematic As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSendCountManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSendCountManual As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSendCountSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSendCountSerial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSendCountNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSendCountNews As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSubscriberCountSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubscriberCountSerial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSubscriberCountNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubscriberCountNews As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSubscriptionSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubscriptionSerial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSubscriptionNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubscriptionNews As Global.System.Web.UI.WebControls.Label
End Class
