'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1
    
    '''<summary>
    '''Bootstrap_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bootstrap_Panel As Global.RVAS.Bootstrap_Panel
    
    '''<summary>
    '''txtTableSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTableSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearch_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch_New As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tblManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblManagement As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblTableFooterDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTableFooterDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnLastPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLastPage As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnNextPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextPage As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnGoPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoPage As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtTablePageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTablePageNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnPreviousPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousPage As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnFirstPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFirstPage As Global.System.Web.UI.WebControls.LinkButton
End Class
