'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OnDemandManualSendReport
    
    '''<summary>
    '''Bootstrap_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bootstrap_Panel As Global.RVAS.Bootstrap_Panel
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cmbVASServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbVASServices As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Bootstrap_PersianDateTimePicker_From control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bootstrap_PersianDateTimePicker_From As Global.RVAS.Bootstrap_PersianDateTimePicker
    
    '''<summary>
    '''Bootstrap_PersianDateTimePicker_To control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bootstrap_PersianDateTimePicker_To As Global.RVAS.Bootstrap_PersianDateTimePicker
    
    '''<summary>
    '''rdoShowSummaryYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoShowSummaryYes As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdoShowSummaryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoShowSummaryNo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdoIsAscendingSortYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoIsAscendingSortYes As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdoIsAscendingSortNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoIsAscendingSortNo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''tblReport_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblReport_Detail As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''tblReport_Summary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblReport_Summary As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblSummarySum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummarySum As Global.System.Web.UI.WebControls.Label
End Class
